add-windowsfeature -name Web-Server
add-windowsfeature -name Web-App-Dev
add-windowsfeature -name Web-Asp-Net
add-windowsfeature -name Web-Net-Ext
add-windowsfeature -name Web-ASP
add-windowsfeature -name Web-ISAPI-Ext
add-windowsfeature -name Web-ISAPI-Filter
add-windowsfeature -name Web-Health
add-windowsfeature -name Web-ODBC-Logging
add-windowsfeature -name Web-Security
add-windowsfeature -name Web-Basic-Auth
add-windowsfeature -name Web-Windows-Auth
add-windowsfeature -name Web-Performance
add-windowsfeature -name Web-Mgmt-Tools
add-windowsfeature -name Web-Mgmt-Service
add-windowsfeature -name Web-Mgmt-Compat
add-windowsfeature -name Web-Metabase
add-windowsfeature -name Web-Lgcy-Mgmt-Console
remove-windowsfeature -name Web-Http-Redirect
