add-windowsfeature AppHostSvc
add-windowsfeature AppMgmt
add-windowsfeature BITS
add-windowsfeature BFE
add-windowsfeature CertPropSvc
add-windowsfeature EventSystem
add-windowsfeature COMSysApp
add-windowsfeature CryptSvc
add-windowsfeature DcomLaunch
add-windowsfeature UxSms
add-windowsfeature Dhcp
add-windowsfeature DPS
add-windowsfeature TrkWks
add-windowsfeature MSDTC
add-windowsfeature Dnscache
add-windowsfeature fdPHost
add-windowsfeature gpsvc
add-windowsfeature IISADMIN
add-windowsfeature IKEEXT
add-windowsfeature iphlpsvc
add-windowsfeature PolicyAgent
add-windowsfeature NetPipeActivator
add-windowsfeature NetTcpActivator
add-windowsfeature NetTcpPortSharing
add-windowsfeature Netlogon
add-windowsfeature Netman
add-windowsfeature netprofm
add-windowsfeature NlaSvc
add-windowsfeature nsi
add-windowsfeature NSClientpp
add-windowsfeature pla
add-windowsfeature PlugPlay
add-windowsfeature Power
add-windowsfeature Spooler
add-windowsfeature RasMan
add-windowsfeature SessionEnv
add-windowsfeature TermService
add-windowsfeature UmRdpService
add-windowsfeature RpcSs
add-windowsfeature RemoteRegistry
add-windowsfeature RpcEptMapper
add-windowsfeature SstpSvc
add-windowsfeature SamSs
add-windowsfeature LanmanServer
add-windowsfeature ShellHWDetection
add-windowsfeature SMTPSVC
add-windowsfeature Symantec AntiVirus
add-windowsfeature ccEvtMgr
add-windowsfeature SmcService
add-windowsfeature ccSetMgr
add-windowsfeature SENS
add-windowsfeature Schedule
add-windowsfeature lmhosts
add-windowsfeature TapiSrv
add-windowsfeature ProfSvc
add-windowsfeature VMTools
add-windowsfeature VMUpgradeHelper
add-windowsfeature eventlog
add-windowsfeature MpsSvc
add-windowsfeature Winmgmt
add-windowsfeature WAS
add-windowsfeature WinRM
add-windowsfeature W32Time
add-windowsfeature wuauserv
add-windowsfeature LanmanWorkstation
add-windowsfeature W3SVC