add-windowsfeature -name Web-Server
add-windowsfeature -name Application-Server
add-windowsfeature -name AS-NET-Framework
add-windowsfeature -name AS-TCP-Port-Sharing
add-windowsfeature -name AS-WAS-Support
add-windowsfeature -name AS-HTTP-Activation
add-windowsfeature -name AS-Dist-Transaction
add-windowsfeature -name AS-Incoming-Trans
add-windowsfeature -name AS-Outgoing-Trans
add-windowsfeature -name AS-WS-Atomic
add-windowsfeature -name Web-Http-Redirect
add-windowsfeature -name Web-App-Dev
add-windowsfeature -name Web-Asp-Net
add-windowsfeature -name Web-Net-Ext
add-windowsfeature -name Web-ASP
add-windowsfeature -name Web-ISAPI-Ext
add-windowsfeature -name Web-ISAPI-Filter
add-windowsfeature -name Web-Health
add-windowsfeature -name Web-Security
add-windowsfeature -name Web-Performance
add-windowsfeature -name Web-Dyn-Compression
add-windowsfeature -name Web-Mgmt-Tools
add-windowsfeature -name Web-Mgmt-Service
add-windowsfeature -name Web-Mgmt-Compat
add-windowsfeature -name Web-Metabase
add-windowsfeature -name Web-Lgcy-Mgmt-Console
add-windowsfeature -name NET-Framework
add-windowsfeature -name NET-HTTP-Activation
add-windowsfeature -name XPS-Viewer
add-windowsfeature -name SMTP-Server
add-windowsfeature -name SNMP-Services
add-windowsfeature -name SNMP-Service
add-windowsfeature -name Telnet-Client
add-windowsfeature -name Powershell-ISE
add-windowsfeature -name WAS
add-windowsfeature -name Backup-Features
add-windowsfeature -name Backup
add-windowsfeature -name Backup-Tools
remove-windowsfeature -name AS-MSMQ-Activation
remove-windowsfeature -name Web-CGI
remove-windowsfeature -name Web-Includes
add-windowsfeature -name RSAT
add-windowsfeature -name RSAT-Feature-Tools
add-windowsfeature -name RSAT-SMTP